buying   = ['vhigh','high','med','low']
maint    = ['vhigh','high','med','low']
door     = ['2','3','4','5more']
persons  = ['2','4','more']
lug_boot = ['small','med','big']
safety   = ['low','med','high']
car_cols = [buying,maint,door,persons,lug_boot,safety]
car_col_names = ['Buying','Maint','Doors','Persons','Lug_boot','Safety']
