* Assignment Summary

When your assignment is complete, please answer the questions in this text file
and upload it to I-Learn.

Name: Jacob Alldredge

1. Please provide the URL of your public GitHub repository.
   Course Repo
   - https://github.com/jkalldre/cs450

   Prove01 Repo
   - https://github.com/jkalldre/cs450/tree/master/python/01Prove 

For questions 2-6, please type "True" or "False" in front of the question number.

TRUE 2. My experiment shell can correctly load the Iris dataset:

TRUE 3. My experiment shell randomizes the order of the instances (making sure to
        keep instances lined up with their appropriate targets) it and splits the
        data into a training set (70%) and a test set (30%)?

TRUE 4. I have created a HardCoded classifier class with two methods: train(fit) and
        predict. The train method accepts training data (including targets). The
        predict method returns a prediction or classification for each instance it
        receives.

TRUE 5. The Experiment Shell, processes the data, passes the training data to the
        classifier's train method, the test data to the predict method, and then
        compares the predicted values against the correct answers, to produce an
        overall accuracy (on the test set).

TRUE 6. I have run the HardCoded classifier on the Iris dataset and obtained a result.

     7. What accuracy do you get when running the HardCoded classifier on the Iris
        dataset and why do you think that is?

        I got a 44.44% after multiple attempts at running, this is because my predict()
        function returns an array of all 0s. Since my test_{} set is chosen at random each
        time that the program is run there will be a different ratio of 0s selected from
        the over all dataset.

8. Please select the category you feel best describes your assignment:

1 - Some attempt was made

2 - Developing, but signficantly deficient

3 - Slightly deficient, but still mostly adequate

4 - Meets requirements

--[5 - Shows creativity and excels above and beyond requirements]--

9. Provide a brief justification (1-2 sentences) for selecting that category:
   - I think I deserve a 5.
   - I implemented a function called loadCSV that will allow you to load a large
     dataset from either a .csv file or from a url.
   - I made it possible to run either the GaussianNB or the HardCodedClassifier
     depending on input given.
